-- AlterTable
ALTER TABLE "Leave" ALTER COLUMN "fromDate" DROP NOT NULL,
ALTER COLUMN "fromDate" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "toDate" DROP NOT NULL,
ALTER COLUMN "toDate" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(3);
